apiVersion: apps/v1
kind: Ingress
metadata:
  name: node-ingress

spec:
  rules:
    -host: devops-app.local

    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-service
            port:
              number: 80