pipeline{
    agent any 

    environment {
        DOCKER_IMAGE = "devops-node-app"
    }

stages {
    stage ("clone repo") {
        steps {
            git 'https://github.com/Kumaranvelan/devops-production-project'
        }
    }

    stage ("Build Docker Image") {
        steps {
            sh 'docker build -t $DOCKER_IMAGE ./app'
        }
    }

    stage ( "Push Docker Image") {
        steps {
            sh 'docker tag $DOCKER_IMAGE johnvelan/devops-node-app'
            sh 'docker push johnvelan/devops-node-app'
        }
    }
    stage ("Deploy to kubernetes") {
        steps{
            sh 'kubectl apply -f k8s/'
        }
    }
}

}