pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "johnvelan/devops-node-app"
        DOCKER_TAG = "latest"
    }

    stages {
        stage("Clone Repo") {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Kumaranvelan/devops-production-project'
            }
        }

        stage("Build Docker Image") {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:$DOCKER_TAG ./app'
            }
        }

        stage("Push Docker Image") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push $DOCKER_IMAGE:$DOCKER_TAG'
                }
            }
        }

        stage("Deploy to Kubernetes") {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline succeeded!'
        }
        failure {
            echo '❌ Pipeline failed!'
        }
    }
}
